### ISSUE TITLE
Summary does not count errors

### ISSUE THREAD

**Issue by philippgerard** [verkkokauppacom/parallel-phpunit#10]
Now that my tests actually work, I noticed that errors are not counted in the summary which is printed all the time.

Check out my proof: http://cl.ly/image/3q1w0x3K320y

**Comment by siivonen** [comment]
Summary results are counted from the phpunit execution output (the progress lines like ..S....E.F... ). From the screenshot I can't see if there are any lines with F in the failing phpunit output. You could show some more of the failing phpunit command ouput.

Parallel-phpunit might count the summary lines incorrectly if test execution just dies or if it outputs something in between the progress lines.

**Comment by philippgerard** [comment]
I can confirm that "F" output is not counted.

I'm using the coloured output from phpunit, could that be the reason?

**Comment by philippgerard** [comment]
Yep, I can confirm that colors="false" in phpunit.xml solves the issue. Another bug! ;)

**Comment by siivonen** [comment]
Yes, the color character messed up summary line counting. Just pushed a fix to this problem.

**Comment by philippgerard** [comment]
Works! Thanks :+1:
