### ISSUE TITLE
Mark test as failed when PHP error, warning, ... occured

### ISSUE THREAD

**Issue by howkey666** [verkkokauppacom/parallel-phpunit#13]
When test ends for example with this warning: 

PHP Warning:  require_once(/home/extranet/web/library/Config.php): failed to open stream

Then should be marked as failed. It helps to run tests in parallel automatically and checks only the last line "Success: 542 Fail: 0 Error: 0 Skip: 0 Incomplete: 0"

**Comment by siivonen** [comment]
This is now fixed. A failing phpunit process that has no test failures is considered to be one failed test.
