### ISSUE TITLE
Add parameter for less ouput

### ISSUE THREAD

**Issue by howkey666** [verkkokauppacom/parallel-phpunit#14]
What about adding new parameter for less output, or parameter for more output like a --pu--verbose? I think that is enough to write on output only this line:

Success: 536 Fail: 0 Error: 0 Skip: 0 Incomplete: 0

after succesfully performed test. And if test ends with error, then should by good to write output from test. That helps to better orientation in output

**Comment by siivonen** [comment]
This is now done and documentation updated. I also created new release (1.3.0) which contains the new --pu-verbose switch. Thanks for the good idea!
