### ISSUE TITLE
Return 0 exit code when some test failed or 1 exit code when all tests ran fine

### ISSUE THREAD

**Issue by howkey666** [verkkokauppacom/parallel-phpunit#15]
It would be great if the parallel-phpunit could return 0 exit code when some test failed and 1 exit code if all tests ran fine.

**Comment by razielsd** [comment]
You can try this version: https://github.com/razielsd/parallel-phpunit2 , but here is lighter.

**Comment by howkey666** [comment]
I do not wanna try another version. This version is really what i want, one file containing wrapper which allow me to run PHPUnit tests in parallel.

**Comment by razielsd** [comment]
Here must be return exit code 1 when error:
https://github.com/verkkokauppacom/parallel-phpunit/blob/master/bin/parallel-phpunit#L250

**Comment by tovrleaf** [comment]
@howkey666 parallel-phpunit is a bash script.

From The Linux Documentation Project:
"A successful command returns a 0, while an unsuccessful one returns a non-zero value that usually can be interpreted as an error code. Well-behaved UNIX commands, programs, and utilities return a 0 exit code upon successful completion" - http://tldp.org/LDP/abs/html/exit-status.html

What's the use-case for this? I'd prefer to leave the exit status as it is.

**Comment by howkey666** [comment]
Sorry! I'm an idiot! I wrote the title of this issue wrong.... Of Course the parallel-phpunit should return 0 on success, 1 on error The second thing is, that i wrote this before I checked the returned exit codes :(
