### ISSUE TITLE
Comparison to https://github.com/brianium/paratest

### ISSUE THREAD

**Issue by Krinkle** [verkkokauppacom/parallel-phpunit#16]
I've used `parallel-phpunit` in various small projects and like it a lot for its simplicity. However it has obvious drawbacks and limitations. It seems someone else has taken the effort of going the extra mile.

Would it be interesting to seek a collaboration with https://github.com/brianium/paratest?  I think both projects would benefit from it.

**Comment by razielsd** [comment]
@siivonen want be simple :) I'm offer to new version (#11), but he decline :(
