### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by schickling** [verkkokauppacom/parallel-phpunit#6]
Please make this package available via https://packagist.org/

I think that way you get a lot more feedback and improvement suggests :+1:

**Comment by razielsd** [comment]
Why not pear ? pecl ?

**Comment by razielsd** [comment]
This project is shell script, see code before spam :)

**Comment by schickling** [comment]
@razielsd Yes, but since Composer is the "new and better pear" I thought it would be useful to have it available via Composer ;)

**Comment by razielsd** [comment]
@schickling relax, here bash-script, not php.

**Comment by philippgerard** [comment]
FYI: Composer supports many languages, not just PHP ;). There's even a composer bundled selenium jar available.

**Comment by razielsd** [comment]
bash supported ?

**Comment by philippgerard** [comment]
http://getcomposer.org/doc/articles/vendor-binaries.md ?

**Comment by razielsd** [comment]
Anyone want create package ?

**Comment by schickling** [comment]
I don't want to push you but imo it would be the best if you would prepare the repo on your own first.
Since composer allows dependencies you could set phpunit as a dependency. If you do so please use the phpunit script from /vendor/bin/phpunit as default.

Beside this decision it should be as simple as adding a composer.json file to your repo and simply register your github repo on packagist. No further maintenance required. :+1: 

If you still want someone to do this, let us know.

**Comment by siivonen** [comment]
I added the composer support: https://packagist.org/packages/verkkokauppacom/parallel-phpunit

There is now only version dev-master available. We will make release 1.3.0 in few weeks. All the future releases will be available automatically by Composer. Let me know if something is not working for you.

**Comment by schickling** [comment]
Awesome @siivonen I'll check it out as soon as i can! :+1: 

Works so far, but i got a few improvement ideas, some concerning composer in particular. I'll create a new issue https://github.com/verkkokauppacom/parallel-phpunit/issues/8 for that. Thanks so far for your work!
