### ISSUE TITLE
Use phpunit from composer when using it

### ISSUE THREAD

**Issue by schickling** [verkkokauppacom/parallel-phpunit#8]
If you installed parallel-phpunit using composer it should use ./vendor/bin/phpunit as default command and not the global installation. (In my case, I even deleted the global installation since I have phpunit shipped with a project using composer).

So at the moment I have to run the following command
`./vendor/bin/parallel-phpunit --pu-cmd vendor/bin/phpunit .`

More convenient would be just 
`./vendor/bin/parallel-phpunit .`

**Comment by siivonen** [comment]
Wouldn't you want to add your vendor/bin as the first item in your PATH?

```
export PATH=<root>/vendor/bin:$PATH
```

This way you can use the Composer installed binaries without any prefixes, like:

```
parallel-phpunit .
phpunit .
```

Or are you always running the project binaries with reference path?

**Comment by schickling** [comment]
Thanks for your reply. Of course this would be an option, but I would have to replace <root> for each project in my bash config. So thats not very flexible imo.

**Comment by siivonen** [comment]
Just pushed a fix for this issue. Hope it works for you!

**Comment by schickling** [comment]
Works! Thanks!
